name: Build
on:
  push:
    branches-ignore:
      - gh-pages
      - "releases/**"
    tags-ignore:
      - "v*"
  pull_request:
    branches-ignore:
      - gh-pages
      - "releases/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"
          cache: "maven"
      - name: fix mvnw unix issues
        run: chmod +x mvnw
      - name: build with Maven
        run: ./mvnw -B -U package

  sonarcloud:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"
          cache: "maven"
      - name: change mvnw permission
        run: chmod +x mvnw
      - name: analyze in sonarcloud with maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw -B -U verify sonar:sonar

  website:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"
          cache: "maven"
      - name: change mvnw permission
        run: chmod +x mvnw
      - name: build website with maven
        run: ./mvnw -B -U site:site site:stage
